name: Create Draft Release

on:
  push:
    branches:
    - main

jobs:
  smoke:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:

    - name: Install Pack
      run : |
        (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.13.1/pack-v0.13.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
        sudo chmod +x /usr/local/bin/pack

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: builder-repo

    - name: Checkout paketo samples
      uses: actions/checkout@v2
      with:
        repository: paketo-buildpacks/samples
        path: samples

    - name: Run smoke tests
      run: |
        pack create-builder testbuilder --config builder-repo/builder.toml
        pack build testapp -p samples/nodejs/yarn --builder testbuilder
        pack build testapp -p samples/go/mod --builder testbuilder
        pack build testapp -p samples/java/maven --builder testbuilder

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: smoke
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
    - name: Reset Draft Release
      id: reset
      uses: paketo-buildpacks/github-config/actions/release/reset-draft@main
      with:
        repo: ${{ github.repository }}
        token: ${{ github.token }}
    - name: Tag
      id: tag
      uses: paketo-buildpacks/github-config/actions/tag@main
      with:
        current_version: ${{ steps.reset.outputs.current_version }}
    - name: Create Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: v${{ steps.tag.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: v${{ steps.tag.outputs.tag }}
        body: "See builder.toml file"
        draft: true
